// Editorial ingredient evidence. Packaged products must satisfy the stated specification.
// Traits drive dietary tags; allergens are ingredient warnings, never cross-contact guarantees.
const item=(name,traits=[],allergens=[],notes=null)=>({name,traits,allergens,notes});
const packaged='Check package labels; use the specified dietary version and check additional allergens and cross-contact notices.';
export const ingredients={
 chickpeas:item('canned chickpeas',[],[],`Drained and rinsed; quantities are drained. ${packaged}`),
 blackBeans:item('canned black beans',[],[],`Drained and rinsed; quantities are drained. ${packaged}`),
 kidneyBeans:item('canned kidney beans',[],[],`Drained and rinsed; quantities are drained. ${packaged}`),
 pintoBeans:item('canned pinto beans',[],[],`Drained and rinsed; quantities are drained. ${packaged}`),
 whiteBeans:item('canned white beans',[],[],`Drained and rinsed; quantities are drained. ${packaged}`),
 lentils:item('cooked lentils',[],[],`Drained; use canned or refrigerated ready-cooked lentils. ${packaged}`),
 redLentils:item('dry split red lentils',[],[],`Rinsed; gluten-free labelled if needed. ${packaged}`),
 rice:item('dry long-grain white rice',[],[],packaged),
 cookedRice:item('ready-cooked rice',[],[],`Use a fresh sealed plain rice pouch or rice promptly chilled and refrigerated. ${packaged}`),
 brownRice:item('ready-cooked brown rice',[],[],`Use a fresh sealed plain rice pouch or promptly chilled refrigerated rice. ${packaged}`),
 pasta:item('dry egg-free wheat pasta',['gluten'],['Wheat'],packaged),
 gfPasta:item('dry gluten-free rice pasta',[],[],packaged),
 noodles:item('dry rice noodles',[],[],`Choose a gluten-free variety that cooks in 4–6 minutes. ${packaged}`),
 bread:item('vegan sliced wheat bread',['gluten'],['Wheat'],packaged),
 tortilla:item('vegan wheat tortillas',['gluten'],['Wheat'],packaged),
 cornTortilla:item('gluten-free corn tortillas',[],[],packaged),
 flatbread:item('vegan wheat flatbread',['gluten'],['Wheat'],packaged),
 bun:item('vegan wheat burger buns',['gluten'],['Wheat','Soy','Sesame'],`Choose dairy-free and egg-free buns; may contain soy and sesame. ${packaged}`),
 pita:item('vegan wheat pita',['gluten'],['Wheat'],packaged),
 couscous:item('dry wheat couscous',['gluten'],['Wheat'],packaged),
 quinoa:item('dry quinoa',[],[],`Rinsed. ${packaged}`),
 polenta:item('quick-cooking corn polenta',[],[],`Choose a gluten-free 5-minute variety. ${packaged}`),
 oats:item('certified gluten-free rolled oats',[],[],packaged),
 flour:item('all-purpose wheat flour',['gluten'],['Wheat'],`Do not taste raw flour or uncooked batter. ${packaged}`),
 breadcrumbs:item('vegan wheat breadcrumbs',['gluten'],['Wheat'],packaged),
 barley:item('dry pearl barley',['gluten'],[],packaged),
 chicken:item('raw boneless skinless chicken breast',['meat'],[], 'Thawed in the refrigerator; not frozen.'),
 chickenThigh:item('raw boneless skinless chicken thighs',['meat'],[], 'Thawed in the refrigerator; not frozen.'),
 cookedChicken:item('plain fully cooked chicken',['meat'],[],`Use refrigerated ready-to-eat chicken within its safe storage period. ${packaged}`),
 beef:item('raw lean ground beef',['meat'],[], 'Keep refrigerated until cooking.'),
 steak:item('raw beef sirloin steak',['meat'],[], 'Intact, not mechanically tenderized; keep refrigerated.'),
 turkey:item('raw ground turkey',['meat'],[], 'Keep refrigerated until cooking.'),
 salmon:item('raw salmon fillets',['fish'],['Fish'],'Thawed, boneless; check for pin bones.'),
 cod:item('raw cod fillets',['fish'],['Fish'],'Thawed, boneless; check for pin bones.'),
 trout:item('raw trout fillets',['fish'],['Fish'],'Thawed, boneless; check for pin bones.'),
 shrimp:item('raw peeled shrimp',['fish'],['Shellfish'],'Thawed, deveined; tails removed.'),
 tuna:item('canned tuna',['fish'],['Fish'],`Drained, packed in water. ${packaged}`),
 sardines:item('canned sardines',['fish'],['Fish'],`Drained; ready to eat. ${packaged}`),
 tofu:item('plain firm tofu',[],['Soy'],`Drained and patted dry; gluten-free labelled if needed. ${packaged}`),
 edamame:item('frozen shelled edamame',[],['Soy'],packaged),
 eggs:item('eggs',['egg'],['Eggs'],'Keep refrigerated; discard cracked eggs. Wash hands and tools after handling shells.'),
 yogurt:item('plain pasteurized Greek yogurt',['dairy'],['Milk'],packaged),
 milk:item('pasteurized milk',['dairy'],['Milk'],packaged),
 cheddar:item('microbial-rennet cheddar cheese',['dairy'],['Milk'],`Grated. ${packaged}`),
 mozzarella:item('microbial-rennet mozzarella cheese',['dairy'],['Milk'],`Grated. ${packaged}`),
 feta:item('pasteurized microbial-rennet feta cheese',['dairy'],['Milk'],`Crumbled. ${packaged}`),
 ricotta:item('pasteurized vegetarian ricotta cheese',['dairy'],['Milk'],packaged),
 butter:item('butter',['dairy'],['Milk'],packaged),
 almondMilk:item('unsweetened gluten-free almond milk',[],['Tree nuts'],packaged),
 soyMilk:item('unsweetened gluten-free soy milk',[],['Soy'],packaged),
 coconutMilk:item('canned unsweetened coconut milk',[],[],packaged),
 pesto:item('vegetarian basil pesto',['dairy'],['Milk','Tree nuts'],`Made with microbial-rennet cheese and pine nuts. ${packaged}`),
 hummus:item('plain gluten-free hummus',[],['Sesame'],packaged),
 tahini:item('plain tahini',[],['Sesame'],packaged),
 peanutButter:item('smooth peanut butter',[],['Peanuts'],packaged),
 peanuts:item('unsalted roasted peanuts',[],['Peanuts'],packaged),
 walnuts:item('unsalted walnuts',[],['Tree nuts'],packaged),
 sesame:item('sesame seeds',[],['Sesame'],packaged),
 tamari:item('gluten-free tamari',[],['Soy'],packaged),
 miso:item('gluten-free rice miso',[],['Soy'],packaged),
 mustard:item('prepared gluten-free mustard',[],['Mustard'],packaged),
 kimchi:item('vegan gluten-free kimchi',[],[],`Must contain no fish or shrimp. ${packaged}`),
 broth:item('gluten-free vegan vegetable broth',[],[],packaged),
 tomatoSoup:item('vegetarian tomato soup',['gluten','dairy'],['Milk','Wheat'],`Ready-to-heat, not condensed; choose vegetarian. ${packaged}`),
 cannedTomato:item('canned diced tomatoes',[],[],`Include juices. ${packaged}`),
 sauce:item('plain gluten-free vegan tomato sauce',[],[],packaged),
 tomatoPaste:item('plain tomato paste',[],[],packaged),
 salsa:item('mild gluten-free vegan salsa',[],[],packaged),
 corn:item('frozen corn kernels',[],[],packaged),
 peas:item('frozen green peas',[],[],packaged),
 oil:item('olive oil'), sesameOil:item('toasted sesame oil',[],['Sesame']),
 water:item('water'), salt:item('fine salt'), pepper:item('ground black pepper'),
 lemon:item('lemon juice'), lime:item('lime juice'), vinegar:item('unseasoned rice vinegar'),
 maple:item('pure maple syrup'), honey:item('honey',['honey']),
 curry:item('mild gluten-free curry powder',[],['Mustard'],`Choose a blend with no dairy; blends may contain mustard. ${packaged}`),
 chiliPowder:item('mild gluten-free chili powder',[],[],`Choose a dairy-free blend. ${packaged}`),
 cajun:item('hot gluten-free Cajun seasoning',[],[],`Choose dairy-free. ${packaged}`),
 cumin:item('ground cumin'), paprika:item('smoked paprika'), cinnamon:item('ground cinnamon'),
 turmeric:item('ground turmeric'), chili:item('red pepper flakes'),
 oregano:item('dried oregano'), thyme:item('dried thyme'), bakingPowder:item('baking powder',[],[],packaged),
 potato:item('potatoes'), sweetPotato:item('sweet potatoes'), avocado:item('avocado'),
 cucumber:item('cucumber'), tomato:item('tomatoes'), cherryTomato:item('cherry tomatoes'),
 garlic:item('garlic'), ginger:item('fresh ginger'), onion:item('yellow onion'), scallion:item('scallions'),
 carrot:item('carrots'), cabbage:item('green cabbage'), lettuce:item('lettuce'), greens:item('mixed salad greens'),
 spinach:item('baby spinach'), kale:item('kale'), broccoli:item('broccoli florets'), cauliflower:item('cauliflower florets'),
 greenBeans:item('green beans'), bellPepper:item('bell peppers'), mushroom:item('mushrooms'),
 zucchini:item('zucchini'), eggplant:item('eggplant'), squash:item('butternut squash'), celery:item('celery'),
 radish:item('radishes'), cornFresh:item('fresh corn kernels'), asparagus:item('asparagus'),
 jalapeno:item('jalapeño'), basil:item('fresh basil'), parsley:item('fresh parsley'), cilantro:item('fresh cilantro'), dill:item('fresh dill'),
 olives:item('pitted olives',[],[],packaged), apple:item('apple'), banana:item('banana'), berries:item('fresh berries'),
 pear:item('pear'), orange:item('orange segments'), raisins:item('unsulphured raisins',[],[],packaged),
 pumpkin:item('plain canned pumpkin',[],[],packaged), cocoa:item('unsweetened cocoa powder',[],[],packaged),
};
export function dietTags(keys){
 const traits=new Set(keys.flatMap(k=>ingredients[k].traits)); const tags=[];
 if(!traits.has('meat'))tags.push('pescatarian');
 if(!traits.has('meat')&&!traits.has('fish'))tags.push('vegetarian');
 if(!['meat','fish','egg','dairy','honey'].some(x=>traits.has(x)))tags.push('vegan');
 if(!traits.has('gluten'))tags.push('gluten-free');
 if(!traits.has('dairy'))tags.push('dairy-free');
 return tags;
}
