import {readFile,writeFile} from 'node:fs/promises';
import {ownedRecipes} from '../server/recipes/owned/catalog.js';
import {drafts} from '../server/recipes/owned/recipes.js';
const legacy=JSON.parse(await readFile(new URL('../server/recipes/owned/legacy-picker-metadata.json',import.meta.url)));
export const pickerMeals=ownedRecipes.map((recipe,index)=>{
 const d=drafts[index],old=legacy[d.id];
 const fresh=d.mealTypes.some(x=>['salad','lunch','snack'].includes(x));
 return {id:d.id,name:recipe.title,emoji:old?.emoji||(d.mealTypes.includes('soup')?'🥣':d.mealTypes.includes('breakfast')?'🍳':'🍽️'),cuisine:recipe.cuisine,mood:old?.mood||(d.heat>0?['bold','comfort']:fresh?['fresh']:['comfort']),minutes:recipe.time.totalMinutes,cost:d.cost,heat:d.heat,adventure:d.adventure,diets:recipe.dietTags,description:recipe.description,ingredients:recipe.ingredients.map(i=>i.name),knownAllergens:recipe.knownAllergens};
});
const generated='// Generated by pnpm catalog:generate; edit server/recipes/owned/ instead. No directions shipped in picker bundle.\nexport const meals = '+JSON.stringify(pickerMeals,null,2)+';\n';
const report=`# EZEATS original recipe editorial review\n\nReviewed ${ownedRecipes[0].editorial.reviewedAt}. Exactly ${ownedRecipes.length} original EZEATS recipes. AI-assisted editorial review is not owner approval, professional food-safety validation or kitchen testing. Every recipe needs owner review and kitchen testing before being described as tested. No recipe images are used.\n\nTags apply to the exact specified products. Allergen lists include known ingredients and deliberately conservative product-dependent warnings, not absence-of-cross-contact guarantees. Times and USD per-serving budgets are editorial estimates, not measured results or live prices; Canadian prices differ.\n\n| Recipe ID | Title | Servings | Total min | Diet tags | Known allergens | Owner review | Kitchen testing |\n|---|---|---:|---:|---|---|---|---|\n`+ownedRecipes.map(r=>`| ${r.id} | ${r.title} | ${r.servings} | ${r.time.totalMinutes} | ${r.dietTags.join(', ')||'None'} | ${r.knownAllergens.join(', ')||'None identified in specified ingredients; check labels'} | Required | Not performed |`).join('\n')+'\n';
const outputs=[['dist/meal-catalog.js',generated],['docs/recipe-review-report.md',report]];
for(const [path,content] of outputs){const url=new URL('../'+path,import.meta.url);if(process.argv.includes('--check')){if(await readFile(url,'utf8')!==content)throw new Error(`Stale generated file: ${path}`);}else await writeFile(url,content);}
console.log(`${pickerMeals.length} recipe summaries and review rows ${process.argv.includes('--check')?'verified':'generated'}.`);
